cmake_minimum_required (VERSION 3.22...5.1.0)

if (CMAKE_VERSION VERSION_GREATER_EQUAL "3.24.0")
    cmake_policy(SET CMP0135 NEW)
	cmake_policy(SET CMP0091 NEW)
endif()

project(tiny_gui
	VERSION 0.0.1
	DESCRIPTION "Cross-Platform Tiny `C` GUI"
    LANGUAGES C
)

set(CMAKE_C_STANDARD 90)

include(FetchContent)
include(CheckLibraryExists)
include(CMakePackageConfigHelpers)
include(CMakeDependentOption)
include(GNUInstallDirs)
include(CTest)

set(BUILD_DIR ${CMAKE_SOURCE_DIR}/build)
set(CMAKE_RUNTIME_OUTPUT_DIRECTORY ${BUILD_DIR})
set(CMAKE_ARCHIVE_OUTPUT_DIRECTORY "${CMAKE_SOURCE_DIR}/built")
set(CMAKE_MODULE_PATH "${CMAKE_CURRENT_SOURCE_DIR}/cmake")

set(CMAKE_EXPORT_COMPILE_COMMANDS ON)
set(CMAKE_WINDOWS_EXPORT_ALL_SYMBOLS ON)

option(BUILD_SHARED_LIBS "Build the library as a shared (dynamically-linked) " OFF)

message("Generated with config types: ${CMAKE_CONFIGURATION_TYPES}")
set(CMAKE_CONFIGURATION_TYPES=Debug;Release)

if(UNIX)
    if(APPLE)
        set(CMAKE_C_FLAGS_DEBUG "${CMAKE_C_FLAGS_DEBUG} -D USE_DEBUG")
        set(CMAKE_C_FLAGS "${CMAKE_C_FLAGS} -Wabi -D _DARWIN_UNLIMITED_SELECT=1 -D _DARWIN_USE_64_BIT_INODE=1")
    else()
		set(CMAKE_C_FLAGS_DEBUG "${CMAKE_C_FLAGS_DEBUG} -rdynamic -no-pie -D USE_DEBUG")
    endif()
    set(CMAKE_C_FLAGS "${CMAKE_C_FLAGS} -Wno-format -fno-strict-aliasing -Wstrict-prototypes")
else()
    set(CMAKE_C_FLAGS_DEBUG "${CMAKE_C_FLAGS_DEBUG} /D USE_DEBUG")
endif()

if(APPLE)
	if(BUILD_SHARED_LIBS)
		add_library(${PROJECT_NAME} SHARED ${CMAKE_CURRENT_SOURCE_DIR}/src/gui.c)
	else()
		add_library(${PROJECT_NAME} STATIC ${CMAKE_CURRENT_SOURCE_DIR}/src/gui.c)
	endif()
	find_library(COCOA_LIBRARY Cocoa required)
	target_link_libraries(${PROJECT_NAME} ${COCOA_LIBRARY})
else()
	if(WIN32)
		if(BUILD_SHARED_LIBS)
			add_library(${PROJECT_NAME} SHARED ${CMAKE_CURRENT_SOURCE_DIR}/src/gui.c)
		else()
			add_library(${PROJECT_NAME} STATIC ${CMAKE_CURRENT_SOURCE_DIR}/src/gui.c)
		endif()
		target_link_libraries(${PROJECT_NAME} gdi32 comctl32 )
	else()
		find_package(X11 REQUIRED COMPONENTS Xmu Xt)
		find_library(X11_Xaw_LIB Xaw)
		find_package(OpenGL REQUIRED COMPONENTS GLX)
		if(BUILD_SHARED_LIBS)
			add_library(${PROJECT_NAME} SHARED
				${CMAKE_CURRENT_SOURCE_DIR}/src/gui.c
				${CMAKE_CURRENT_SOURCE_DIR}/src/Linux/TextField.c
				${CMAKE_CURRENT_SOURCE_DIR}/src/Linux/FileSelect.c
				${CMAKE_CURRENT_SOURCE_DIR}/src/Linux/Gridbox.c)
		else()
			add_library(${PROJECT_NAME} STATIC
				${CMAKE_CURRENT_SOURCE_DIR}/src/gui.c
				${CMAKE_CURRENT_SOURCE_DIR}/src/Linux/TextField.c
				${CMAKE_CURRENT_SOURCE_DIR}/src/Linux/FileSelect.c
				${CMAKE_CURRENT_SOURCE_DIR}/src/Linux/Gridbox.c)
		endif()
		target_link_libraries(${PROJECT_NAME} Xaw X11::Xmu X11::Xt X11::X11 OpenGL::GL OpenGL::GLU)
	endif()
endif()
add_library(GUI::TINY ALIAS ${PROJECT_NAME})

target_include_directories(${PROJECT_NAME}
	PRIVATE $<BUILD_INTERFACE:${CMAKE_CURRENT_SOURCE_DIR}/include>)
target_include_directories(${PROJECT_NAME}
    PUBLIC $<INSTALL_INTERFACE:${CMAKE_INSTALL_INCLUDEDIR}>)

# The executable
set(SUB_PROJECT_APP gui_skeleton)
if(APPLE)
	file(GLOB SKELETON_RES ${CMAKE_CURRENT_SOURCE_DIR}resources/skeleton*.*)
	set_source_files_properties(${SKELETON_RES} PROPERTIES MACOSX_PACKAGE_LOCATION Resources)
    add_executable(${SUB_PROJECT_APP} MACOSX_BUNDLE ${CMAKE_CURRENT_SOURCE_DIR}/skeleton.c ${SKELETON_RES})
	set(CPACK_BUNDLE_NAME "${SUB_PROJECT_APP}")
	set(CPACK_BUNDLE_PLIST ${CMAKE_CURRENT_SOURCE_DIR}/resources/info.plist)
	set(CPACK_BUNDLE_ICON ${CMAKE_CURRENT_SOURCE_DIR}/resources/skeleton_64x64.png)
	set(MACOSX_BUNDLE_BUNDLE_VERSION ${PROJECT_VERSION})
	set(MACOSX_BUNDLE_COPYRIGHT "© 2026 ${PROJECT_NAME}")
	set(MACOSX_BUNDLE_INFO_STRING ${PROJECT_DESCRIPTION})
else()
	if(WIN32)
        add_executable(${SUB_PROJECT_APP} ${CMAKE_CURRENT_SOURCE_DIR}/skeleton.c
			${CMAKE_CURRENT_SOURCE_DIR}/resources/res.rc)
	else()
    	add_executable(${SUB_PROJECT_APP} ${CMAKE_CURRENT_SOURCE_DIR}/skeleton.c)
	endif()
endif()

target_link_libraries(${SUB_PROJECT_APP} ${PROJECT_NAME})
target_include_directories(${SUB_PROJECT_APP}
	PRIVATE $<BUILD_INTERFACE:${CMAKE_CURRENT_SOURCE_DIR}/include>)

set_target_properties(${SUB_PROJECT_APP} PROPERTIES
	EXPORT_NAME ${SUB_PROJECT_APP}
    OUTPUT_NAME ${SUB_PROJECT_APP}
	VERSION ${PROJECT_VERSION}
	SOVERSION ${PROJECT_VERSION_MAJOR}
)

install(
	TARGETS ${SUB_PROJECT_APP}
    COMPONENT Runtime
    DESTINATION "${CMAKE_INSTALL_BINDIR}")

set_target_properties(${PROJECT_NAME} PROPERTIES
	OUTPUT_NAME ${PROJECT_NAME}
	ARCHIVE_OUTPUT_NAME ${PROJECT_NAME}
	EXPORT_NAME ${PROJECT_NAME}
	VERSION  ${PROJECT_VERSION}
	SOVERSION ${PROJECT_VERSION_MAJOR}
)

if(NOT CMAKE_VERSION VERSION_LESS 3.27.0)
	set_target_properties(${PROJECT_NAME} PROPERTIES DLL_NAME_WITH_SOVERSION TRUE)
endif()

set(_fmt TGZ)
if(WIN32)
  set(_fmt ZIP)
endif()

set(CPACK_GENERATOR ${_fmt})
set(CPACK_ARCHIVE_COMPONENT_INSTALL ON)
set(CPACK_DEB_COMPONENT_INSTALL ON)
set(CPACK_RPM_COMPONENT_INSTALL ON)
set(CPACK_NUGET_COMPONENT_INSTALL ON)
set(CPACK_WIX_COMPONENT_INSTALL ON)
set(CPACK_NSIS_MODIFY_PATH ON)
set(CPACK_COMPONENTS_ALL_IN_ONE_PACKAGE 1)
set(CPACK_VERBATIM_VARIABLES YES)

set(CPACK_PACKAGE_VENDOR "https://github.com/${PROJECT_NAME}")
set(CPACK_PACKAGE_VERSION ${PROJECT_VERSION})

set(CMAKE_INSTALL_CONFIG_NAME ${CMAKE_BUILD_TYPE})
set(INCLUDE_INSTALL_DIR ${CMAKE_INSTALL_INCLUDEDIR}/"${PROJECT_NAME}"
    CACHE PATH "Location of header files" )

set(SYSCONFIG_INSTALL_DIR ${CMAKE_INSTALL_SYSCONFDIR}/"${PROJECT_NAME}"
    CACHE PATH "Location of configuration files" )

configure_package_config_file(${PROJECT_NAME}Config.cmake.in
  	${CMAKE_CURRENT_BINARY_DIR}/"${PROJECT_NAME}"Config.cmake
	INSTALL_DESTINATION ${CMAKE_INSTALL_LIBDIR}/cmake/"${PROJECT_NAME}"
	PATH_VARS INCLUDE_INSTALL_DIR SYSCONFIG_INSTALL_DIR)

write_basic_package_version_file(
  ${CMAKE_CURRENT_BINARY_DIR}/"${PROJECT_NAME}"ConfigVersion.cmake
  VERSION ${PROJECT_VERSION}
  COMPATIBILITY SameMajorVersion )

set(CPACK_PACKAGE_DIRECTORY "${CMAKE_ARCHIVE_OUTPUT_DIRECTORY}/Package")
set(CPACK_PACKAGE_FILE_NAME "${CPACK_PACKAGE_NAME}-${PROJECT_NAME}")
set(CPACK_PACKAGE_INSTALL_DIRECTORY ${PROJECT_NAME})

set(CPACK_PACKAGE_CONTACT "noreply@github.com")
set(CPACK_DEBIAN_PACKAGE_MAINTAINER "Contributors <${CPACK_PACKAGE_CONTACT}>")
set(CPACK_DEBIAN_FILE_NAME DEB-DEFAULT)

set(CPACK_COMPONENTS_GROUPING ALL_COMPONENTS_IN_ONE)
set(CPACK_COMPONENT_LIBRARIES_DISPLAY_NAME "${PROJECT_NAME}")
set(CPACK_COMPONENT_LIBRARIES_DESCRIPTION ${PROJECT_DESCRIPTION})

set(CPACK_RESOURCE_FILE_LICENSE ${CMAKE_CURRENT_SOURCE_DIR}/LICENSE.md)
set(CPACK_RESOURCE_FILE_README ${CMAKE_CURRENT_SOURCE_DIR}/README.md)

set(CPACK_PACKAGE_VENDOR "https://github.com/${PROJECT_NAME}")
set(CPACK_PACKAGE_VERSION ${PROJECT_VERSION})
set(CPACK_PACKAGE_DESCRIPTION ${PROJECT_DESCRIPTION})

set(CPACK_RPM_PACKAGE_LICENSE "MIT")
set(CPACK_RPM_PACKAGE_URL "https://${PROJECT_NAME}.github.io/${PROJECT_NAME}/")

install(FILES ${CMAKE_CURRENT_BINARY_DIR}/${PROJECT_NAME}Config.cmake
	${CMAKE_CURRENT_BINARY_DIR}/${PROJECT_NAME}ConfigVersion.cmake
	DESTINATION "${CMAKE_INSTALL_LIBDIR}/cmake/${PROJECT_NAME}" )

if(APPLE)
	install(
		TARGETS ${PROJECT_NAME} ${SUB_PROJECT_APP}
		EXPORT "${PROJECT_NAME}Targets"
		ARCHIVE DESTINATION ${CMAKE_INSTALL_LIBDIR}
		LIBRARY DESTINATION ${CMAKE_INSTALL_LIBDIR}
		RUNTIME DESTINATION BUNDLE DESTINATION ${CMAKE_INSTALL_BINDIR}
		PUBLIC_HEADER DESTINATION ${CMAKE_INSTALL_INCLUDEDIR}
		INCLUDES DESTINATION ${CMAKE_INSTALL_INCLUDEDIR}
	)
else()
	install(
		TARGETS ${PROJECT_NAME} ${SUB_PROJECT_APP}
		EXPORT "${PROJECT_NAME}Targets"
		ARCHIVE DESTINATION ${CMAKE_INSTALL_LIBDIR}
		LIBRARY DESTINATION ${CMAKE_INSTALL_LIBDIR}
		RUNTIME DESTINATION ${CMAKE_INSTALL_BINDIR}
		PUBLIC_HEADER DESTINATION ${CMAKE_INSTALL_INCLUDEDIR}
		INCLUDES DESTINATION ${CMAKE_INSTALL_INCLUDEDIR}
	)
endif()

install(
	EXPORT "${PROJECT_NAME}Targets"
	FILE "${PROJECT_NAME}Targets.cmake"
	NAMESPACE ${PROJECT_NAME}::
	DESTINATION "${CMAKE_INSTALL_LIBDIR}/cmake/${PROJECT_NAME}"
)

install(TARGETS ${PROJECT_NAME} DESTINATION lib)
install(TARGETS ${SUB_PROJECT_APP} DESTINATION bin)
install(DIRECTORY include DESTINATION include)
set(CPACK_INSTALL_CMAKE_CONFIGURATIONS Release)

if(NOT EXISTS "${CMAKE_SOURCE_DIR}/resources")
    file(COPY ${CMAKE_CURRENT_SOURCE_DIR}/resources ${CMAKE_SOURCE_DIR}/resources)
endif()