name: Apple M1
on:
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-macos:
    name: macOS
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v6
      - name: Configure & build
        run: |
            mkdir build
            cd build
            cmake -DCMAKE_BUILD_TYPE=Debug -DBUILD_TESTS=ON ..
            cmake --build .
      - name: Disable Firewall
        run: |
          /usr/libexec/ApplicationFirewall/socketfilterfw --getglobalstate
          sudo defaults write /Library/Preferences/com.apple.alf globalstate -int 0
          /usr/libexec/ApplicationFirewall/socketfilterfw --getglobalstate
      - name: Run tests
        run: |
            cd build
            ctest -C Debug --output-on-failure -F
